on:
  pull_request:
    branches:
      - main
name: TOC Generator
jobs:
  generateTOC:
    runs-on: ubuntu-latest
    steps:
    - uses: technote-space/toc-generator@v4.1.2
      with:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TOC_TITLE: "**Inhaltsverzeichnis**"
        # Git commit name.
        COMMIT_NAME: "TOCGEN"
        CREATE_PR: false
        TARGET_PATHS: "./ABWL-LEDER/README.md, ./ASM-GUENTHER/README.md, ./ASM-GUENTHER/appendix/praktikum.md, ./DBS-DORENDORF/README.md, ./PRO-KASCHE/README.md, ./SWE-KASCHE/README.md, ./SWS-KUSCHE/README.md, ./EMB-GUENTHER/README.md, ./OOP-CASSELT/README.md, ./MPP-PI/README.md"
